# Generated by Django 3.2.7 on 2022-01-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_images_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flag',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='images',
            name='product_images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
