# Generated by Django 3.2.4 on 2021-12-20 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestion',
            name='answer',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='question',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
