# Generated by Django 3.2.4 on 2021-12-20 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_auto_20211220_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestion',
            name='user',
        ),
    ]
