# Generated by Django 3.2.4 on 2021-12-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0004_auto_20211222_1517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuestion',
            new_name='Question',
        ),
    ]
