# Generated by Django 3.2.4 on 2021-12-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0005_rename_userquestion_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionmodel',
            name='question',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
