# Generated by Django 3.2.4 on 2021-12-31 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0012_auto_20211230_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
