# Generated by Django 3.2.4 on 2021-12-31 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0013_auto_20211231_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
